<div>
    <h1>
        Bugsnag Zend demo
    </h1>
    <p>
        This Zend application demonstrates the use of Bugsnag with the Zend web framework.
    </p>
    <ol>
        <li>
            <a href="/crash">
                Crash
            </a>
            <br/>
            <p>
                Crashes the application, sending an unhandled notification to Bugsnag.
            </p>
        </li>
        <li>
            <a href="/crashcallbacks">
                Crash and use callbacks
            </a>
            <br/>
            <p>
                Crashes the application, sending an unhandled notification to Bugsnag with additional information included.
            </p>
        </li>
        <li>
            <a href="/notify">
                Notify
            </a>
            <br/>
            <p>
                Manually send a notification to Bugsnag.
            </p>
        </li>
        <li>
            <a href="/notifymetadata">
                Notify with meta data
            </a>
            <br/>
            <p>
                Manually send a notification but with additional metadata, allowing the diagnostics to be more thorough.
            </p>
        </li>
        <li>
            <a href="/notifyseverity">
                Notify with severity
            </a>
            <br/>
            <p>
                Sends a notification to Bugsnag with a custom 
            </p>
        </li>
</div>
